In [1]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import numpy as np
import pandas as pd
import re
from sklearn.feature_extraction.text import CountVectorizer
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\revlis_user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

## Load dataset

In [2]:
message = pd.read_csv('spam.csv', skiprows = [0], usecols=[0, 1], names = ["label","message"], encoding = 'ISO-8859-1')
message

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

## Data Cleaning and Preprocessing

In [3]:
stemmer = PorterStemmer()

In [4]:
corpus = []
for i in range(len(message)):
    review = re.sub("[^a-zA-Z]", " ", message["message"][i])
    review = review.lower()
    review = review.split()
    review = [stemmer.stem(w) for w in review if w not in stopwords.words("english")]
    review = " ".join(review)
    corpus.append(review)

In [5]:
corpus[:20]

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

## Create the bag of word model

In [6]:
cv = CountVectorizer(max_features = 2500) # take top 2500 words with highest frequency

In [7]:
x = cv.fit_transform(corpus).toarray()

In [8]:
list(cv.vocabulary_.items())[:20] # word and index of column

[('go', 870),
 ('point', 1613),
 ('crazi', 493),
 ('avail', 140),
 ('bugi', 272),
 ('great', 894),
 ('world', 2440),
 ('la', 1131),
 ('cine', 391),
 ('got', 885),
 ('wat', 2370),
 ('ok', 1509),
 ('lar', 1143),
 ('joke', 1089),
 ('wif', 2408),
 ('oni', 1517),
 ('free', 809),
 ('entri', 679),
 ('wkli', 2429),
 ('comp', 431)]

In [9]:
x[:30]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [10]:
np.max(x) # highest frequency of words is 18

18

In [11]:
cv1 = CountVectorizer(max_features = 2500, binary = True) # take top 2500 words with highest frequency, binary bow

In [12]:
x1 = cv1.fit_transform(corpus).toarray()

In [13]:
x1[:30]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
np.max(x1) # no frequency, only exist or not

1

## N-grams

N-grams can increase the variance between sentences to get better model performance

In [15]:
cv2 = CountVectorizer(max_features = 2500, ngram_range = (1,2))

In [16]:
x2 = cv2.fit_transform(corpus).toarray()

In [17]:
x2[:30]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [18]:
np.max(x2)

18

In [19]:
list(cv2.vocabulary_.items())[:100] # word and index of column

[('go', 801),
 ('point', 1605),
 ('crazi', 452),
 ('avail', 123),
 ('bugi', 230),
 ('great', 855),
 ('world', 2430),
 ('la', 1084),
 ('cine', 349),
 ('got', 843),
 ('wat', 2338),
 ('ok', 1472),
 ('lar', 1096),
 ('joke', 1051),
 ('wif', 2395),
 ('free', 723),
 ('entri', 617),
 ('wkli', 2419),
 ('comp', 400),
 ('win', 2400),
 ('fa', 653),
 ('cup', 466),
 ('final', 688),
 ('st', 1961),
 ('may', 1265),
 ('text', 2074),
 ('receiv', 1699),
 ('question', 1664),
 ('std', 1976),
 ('txt', 2203),
 ('rate', 1679),
 ('appli', 86),
 ('free entri', 728),
 ('entri wkli', 619),
 ('std txt', 1977),
 ('txt rate', 2209),
 ('rate appli', 1680),
 ('dun', 577),
 ('say', 1795),
 ('earli', 583),
 ('alreadi', 55),
 ('nah', 1386),
 ('think', 2100),
 ('goe', 823),
 ('usf', 2273),
 ('live', 1163),
 ('around', 99),
 ('though', 2110),
 ('freemsg', 735),
 ('hey', 921),
 ('darl', 483),
 ('week', 2363),
 ('word', 2425),
 ('back', 140),
 ('like', 1148),
 ('fun', 755),
 ('still', 1979),
 ('tb', 2052),
 ('xxx', 2465),
 ('